imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    # Serviços de terceiros
    - { resource: services.yml }
    # Serviços da API
    - { resource: "@AuthBundle/Resources/config/services.yml" }
    - { resource: "@PDFBundle/Resources/config/services.yml" }
    - { resource: "@PessoaBundle/Resources/config/services.yml" }
    - { resource: "@CursoBundle/Resources/config/services.yml" }
    - { resource: "@CalendarioBundle/Resources/config/services.yml" }
    - { resource: "@AvaliacaoBundle/Resources/config/services.yml" }
    - { resource: "@VinculoBundle/Resources/config/services.yml" }
    - { resource: "@MatriculaBundle/Resources/config/services.yml" }

parameters:
    locale: pt_BR

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: false 
        # "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
# Sensio converter    
sensio_framework_extra:
    request: { converters: true }
  
# JMS serializer    
jms_serializer:
    property_naming:
        separator:  false
    metadata:
        cache: none
    
# FOS REST
fos_rest:
    disable_csrf_role: ROLE_API
    
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: errors
    
    routing_loader:
        default_format: json
        include_format: false
        
    serializer:
        serialize_null: false

# Nelmio cors
nelmio_cors:
    paths:
        '^/':
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Origin', 'Accept', 'X-WSSE', 'X-Requested-With']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            expose_headers: ['Content-Type', 'Link']
            max_age: 1209600
            hosts: []
            origin_regex: true

# Nelmio doc
nelmio_api_doc:
    sandbox:
        enabled: true
        body_format:
            formats:
                - json
            default_format: json
