services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true
    
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false
    
    wsse.security.authentication.provider:
        class: AuthBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - "" # User Provider
            - "%kernel.cache_dir%/security/nonces"
            - "" 
        public: false

    wsse.security.authentication.listener:
        class: AuthBundle\Security\Firewall\WsseListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
        public: false

        