services:
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        