services:
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        
    Symfony\Bridge\Doctrine\RegistryInterface:
        alias: Doctrine\Common\Persistence\ManagerRegistry
        
    FOS\RestBundle\Request\ParamFetcherInterface:
        alias: fos_rest.request.param_fetcher
        
    FOS\RestBundle\View\ViewHandlerInterface:
        alias: fos_rest.view_handler.default
   
        