services:
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    PessoaBundle\:
        resource: '../../{Service,Listener}'
        
    PessoaBundle\Service\FotoFacade:
        arguments:
            $uploadPath: '%upload_path%'
       
    PessoaBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
          - [setViewHandler, ["@fos_rest.view_handler"]]
    
