PessoaBundle\Entity\Pessoa:
    properties:
        nome:
            - NotBlank: ~
        genero:
            - Choice: [M, F]
        cpfCnpj:
            - Regex: 
                pattern: '/\d/'
                message: "CPF / CNPJ deve possuir apenas dígitos numéricos"
            - Length:
                min: 11
                max: 14
            
PessoaBundle\Entity\PessoaFisica:
    properties:
        certidaoNascimento:
            - Regex:
                pattern: '/[0-9]{32}/'
                message: "Certidão de nascimento deve possuir 32 dígitos numéricos"
            
PessoaBundle\Entity\Telefone:
    properties:
        descricao:
            - Choice: 
                choices: ["RESIDENCIAL", "CELULAR", "COMERCIAL"]