PessoaBundle\Entity\Pessoa:
    properties:
        nome:
            - NotBlank: ~
        dataNascimento:
            - NotNull: ~
        genero:
            - Choice: [M, F]
            
PessoaBundle\Entity\Telefone:
    properties:
        descricao:
            - Choice: [RESIDENCIAL, CELULAR, COMERCIAL]