services:
       
    _defaults:
        autowire: true
        autoconfigure: true
        public: false   
       
    SigAlimentarExtensionBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']