fu_index:
    path:  /admin
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Index:index }

# Serviços públicos

fu_publico_consultarInscricao:
    path: /public/consulta/{protocolo}
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Public:consultarInscricao }
    
fu_publico_consultarChamadas:
    path: /public/chamadas/{zoneamento}
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Public:consultarChamadas }

# Ações da promotoria

fu_promotoria_formFila:
    path: /promotoria/fila
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Promotoria:formFila }
    
fu_promotoria_exibirFila:
    path: /promotoria/fila
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Promotoria:exibirFila }
    
fu_promotoria_formPesquisa:
    path: /promotoria/pesquisar
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Promotoria:formPesquisa }
    
fu_promotoria_pesquisar:
    path: /promotoria/pesquisar
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Promotoria:pesquisar }
    
fu_promotoria_imprimir:
    path: /promotoria/imprimir/{inscricao}
    defaults: { _controller: FilaUnicaBundle:Promotoria:imprimir }
    
fu_promotoria_glossario:
    path: /promotoria/glossario
    defaults: { _controller: FilaUnicaBundle:Promotoria:glossario }
   
# Açõs de gerência - inscrições

fu_inscricao_formFila:
    path: /admin/fila
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:formFila }
    
fu_inscricao_exibirFila:
    path: /admin/fila
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:exibirFila }

fu_inscricao_formPesquisa:
    path: /admin/inscricao/pesquisa
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:formPesquisa }
    
fu_inscricao_pesquisar:
    path: /admin/inscricao/pesquisa
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:pesquisar }
    
fu_inscricao_formInscricao:
    path: /admin/inscricao/cadastrar/{tipoInscricao}
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:formCadastro, tipoInscricao: 1 }
    
fu_inscricao_validar:
    path: /admin/inscricao/validar
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:validar }
   
fu_inscricao_cadastrar:
    path: /admin/inscricao/cadastrar/{tipoInscricao}
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:cadastrar }
    
fu_inscricao_consultar:
    path: /admin/inscricao/{inscricao}
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:consultar }
    
fu_inscricao_imprimirComprovante:
    path: /admin/inscricao/{inscricao}/imprimir/comprovante
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:imprimirComprovante }
    
fu_inscricao_alterar:
    path: /admin/inscricao/{inscricao}/alterar
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:alterar }
    
fu_inscricao_imprimir:
    path: /admin/inscricao/{inscricao}/imprimir/cadastro
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:imprimir }
    
fu_inscricao_cancelar:
    path: /admin/inscricao/{inscricao}/cancelar
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:cancelar }
    
fu_inscricao_imprimirTermoDesistencia:
    path: /admin/inscricao/{inscricao}/imprimir/termo-desistencia
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:imprimirTermoDesistencia }
    
fu_inscricao_incluirTelefone:
    path: /admin/inscricao/{inscricao}/telefones/incluir
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:incluirTelefone }
    
fu_inscricao_excluirTelefone:
    path: /admin/inscricao/{inscricao}/telefones/excluir/{telefone}
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:excluirTelefone }   
    
fu_inscricao_exibirHistorico:
    path: /admin/inscricao/{inscricao}/historico
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:exibirHistorico }
    
fu_inscricao_formOrdemJudicial:
    path: /admin/ordem-judicial
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Inscricao:formOrdemJudicial }
    
fu_inscricao_cadastrarOrdemJudicial:
    path: /admin/ordem-judicial
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:cadastrarOrdemJudicial }
    
fu_inscricao_incluirEvento:
    path: /admin/inscricao/{inscricao}/eventos/incluir
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:incluirEvento }
    
fu_inscricao_excluirEvento:
    path: /admin/eventos/excluir/{evento}
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:excluirEvento }
   
# Ações de gerência - Fila

fu_inscricao_reordenarGeral:
    path: /admin/fila/reordenar
    methods: [GET, POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:reordenarGeral }
    
fu_inscricao_redefinirAnosEscolares:
    path: /admin/fila/redefinir-turmas
    methods: [GET, POST]
    defaults: { _controller: FilaUnicaBundle:Inscricao:redefinirAnosEscolares }
    
# Ações de gerência - Vagas

fu_vaga_formCadastro:
    path: /admin/vaga/cadastrar
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Vaga:formCadastro }
    
fu_vaga_cadastrar:
    path: /admin/vaga/cadastrar
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Vaga:cadastrar }
    
fu_vaga_formPesquisa:
    path: /admin/vaga/pesquisa
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Vaga:formPesquisa }
    
fu_vaga_pesquisar:
    path: /admin/vaga/pesquisa
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Vaga:pesquisar }
    
fu_vaga_preencher:
    path: /admin/vaga/{vaga}/preencher
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Vaga:preencher }
    
fu_vaga_formGerencia:
    path: /admin/vaga/{vaga}/atualizar
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Vaga:formGerencia }
    
fu_vaga_atualizar:
    path: /admin/vaga/{vaga}/atualizar/{status}
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Vaga:atualizar }
    
fu_vaga_cancelar:
    path: /admin/vaga/{vaga}/cancelar
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Vaga:cancelar }
    
fu_vaga_reverterChamada:
    path: /admin/vaga/{vaga}/reverter-chamada
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Vaga:reverterChamada }

# Ações de gerência - Movimentação Interna

fu_movimentacaoInterna_formPesquisa:
    path: /admin/movimentacao-interna/pesquisa
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:formPesquisa }
    
fu_movimentacaoInterna_pesquisar:
    path: /admin/movimentacao-interna/pesquisa
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:pesquisar }

fu_movimentacaoInterna_visualizar:
    path: /admin/movimentacao-interna/{movimentacao}/detalhes
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:visualizar }
       
fu_movimentacaoInterna_imprimirPeriodo:
    path: /admin/movimentacao-interna/imprimir-periodo
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:imprimirPeriodo }

fu_movimentacaoInterna_formCadastro:
    path: /admin/movimentacao-interna/mover-fila
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:formMovimentacaoFila }
    
fu_movimentacaoInterna_cadastrar:
    path: /admin/movimentacao-interna/mover-fila
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:moverFila }
    
fu_movimentacaoInterna_formMovimentacaoVaga:
    path: /admin/movimentacao-interna/{vaga}/mover-vaga
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:formMovimentacaoVaga }
    
fu_movimentacaoInterna_moverVaga:
    path: /admin/movimentacao-interna/{vaga}/mover-vaga
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:MovimentacaoInterna:moverVaga }
  
# Ações de gerência - Unidade Escolar

fu_unidade_escolar_listar:
    path: /admin/unidade-escolar/listar
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:UnidadeEscolar:listar }
   
fu_unidade_escolar_formAlteracao:
    path: /admin/unidade-escolar/{unidade}/alterar
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:UnidadeEscolar:formAlteracao }
    
fu_unidade_escolar_alterar:
    path: /admin/unidade-escolar/{unidade}/alterar
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:UnidadeEscolar:alterar }
    
# Estatísticas e relatórios
    
fu_relatorio_formRelatorioInscricoes:
    path: /admin/relatorio/inscricoes
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Relatorio:formRelatorioInscricoes }
    
fu_relatorio_gerarRelatorioInscricoes:
    path: /admin/relatorio/inscricoes
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Relatorio:gerarRelatorioInscricoes }

fu_relatorio_formRelatorioVagas:
    path: /admin/relatorio/vagas
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Relatorio:formRelatorioVagas }

fu_relatorio_gerarRelatorioVagas:
    path: /admin/relatorio/vagas
    methods: [POST]
    defaults: { _controller: FilaUnicaBundle:Relatorio:gerarRelatorioVagas }
    
fu_relatorio_gerarPrevisaoFila:
    path: /admin/relatorio/previsao
    methods: [GET]
    defaults: { _controller: FilaUnicaBundle:Relatorio:gerarPrevisaoFila }