imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    
    - { resource: "@CommonsBundle/Resources/config/services.yml" }
    - { resource: "@IntranetBundle/Resources/config/services.yml" }
    - { resource: "@PDFBundle/Resources/config/services.yml" }
    - { resource: "@FilaUnicaBundle/Resources/config/services.yml" }
    - { resource: "@DGPBundle/Resources/config/services.yml" }
    - { resource: "@DGPPromocaoBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
    #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: sme
        connections:
            sme:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                mapping_types:
                    enum: string
            moodle:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_moodle%
                user:     %database_user_moodle%
                password: %database_password_moodle%
                charset:  UTF8
                mapping_types:
                    enum: string
            erudio:
                driver:   %database_driver%
                host:     %database_host_erudio%
                port:     %database_port%
                dbname:   %database_name_erudio%
                user:     %database_user_erudio%
                password: %database_password_erudio%
                charset:  UTF8
                mapping_types:
                    enum: string
            #educline:
             #   driver:   %database_driver%
              #  host:     %database_host_educline%
               # port:     %database_port_educline%
                #dbname:   %database_name_educline%
                #user:     %database_user_educline%
                #password: %database_password_educline%
                #charset:  UTF8
               # mapping_types:
                #    enum: string

    orm:
        default_entity_manager: sme
        entity_managers:
          moodle:
            connection: moodle
            mappings:
              MoodleBundle: ~
          
          erudio:
            connection: erudio
            mappings:
              ErudioBundle: ~

          sme:
            connection: sme
            mappings:
              CommonsBundle: ~
              DGPBundle: ~
              DGPContratacaoBundle: ~
              DGPFormacaoBundle: ~
              DGPPromocaoBundle: ~
              DGPPermutaBundle: ~
              DGPProcessoAnualBundle: ~
              FilaUnicaBundle: ~
              IntranetBundle: ~
              PDFBundle: ~
              PresencaBundle: ~
              ProtocoloBundle: ~
              PublicBundle: ~
              SuporteTecnicoBundle: ~
              QuestionarioBundle: ~
              EstagioBundle: ~

        auto_generate_proxy_classes: %kernel.debug%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    #spool:     { type: memory }

jms_security_extra:
    expressions: true

parameters:
  file_store:
    path: %file_store_path%
