security:
    encoders:
        SME\IntranetBundle\Entity\PortalUser:
            id: md5_encoder

    providers:
        main:
            entity:
                class: SME\IntranetBundle\Entity\PortalUser
                property: username
                
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern: ^/[A-Za-z_]+/public/
            security: false
        login:
            pattern:  ^/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: 
                success_handler: security.authentication.success_handler
            logout:
                success_handler: security.logout.success_handler

    access_control:
        # - { path: ^/, requires_channel: https}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/dgp/admin, roles: [ROLE_SUPER_ADMIN, ROLE_DGP_MEMBRO] }
        - { path: ^/fu/admin, roles: [ROLE_SUPER_ADMIN, ROLE_INFANTIL_MEMBRO, ROLE_CEI] }
        - { path: ^/fu/promotoria, roles: [ROLE_SUPER_ADMIN, ROLE_PROMOTORIA] }
        - { path: ^/suporte/admin, roles: [ROLE_SUPER_ADMIN, ROLE_SUPORTE_ADMIN] }
        - { path: ^/suporte, roles: [ROLE_SUPER_ADMIN, ROLE_SUPORTE_USER] }
        - { path: ^/publicacao/admin, roles: [ROLE_SUPER_ADMIN, ROLE_PUBLICACAO_ADMIN] }

