services:
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    MatriculaBundle\:
        resource: '../../{Service,Listener}'
       
    MatriculaBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
          - [setViewHandler, ["@fos_rest.view_handler"]]
    
    MatriculaBundle\Service\MatriculaFacade:
        class: MatriculaBundle\Service\MatriculaFacade
        # Refatorar dependência para evento
        calls:
            - [setUsuarioFacade, ['@AuthBundle\Service\UsuarioFacade']]
