services:
        
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    CursoBundle\:
        resource: '../../{Service,Listener}'
       
    CursoBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
          - [setViewHandler, ["@fos_rest.view_handler"]]