suporte_index:
    path: /
    defaults: { _controller: SuporteTecnicoBundle:Index:index }

# Chamado

suporte_chamado_pesquisar:
    path: /chamado/pesquisar
    defaults: { _controller: SuporteTecnicoBundle:Chamado:pesquisar}
    
suporte_chamado_cadastrar:    
    path: /chamado/cadastrar
    defaults: { _controller: SuporteTecnicoBundle:Chamado:cadastrar }
    
suporte_chamado_gerenciar:    
    path: /chamado/{chamado}/gerenciar
    defaults: { _controller: SuporteTecnicoBundle:Chamado:gerenciar }
    
suporte_chamado_imprimir:    
    path: /chamado/{chamado}/imprimir
    defaults: { _controller: SuporteTecnicoBundle:Chamado:imprimir }
 
 # Atividade
    
suporte_atividade_cadastrar:
    path: /admin/chamado/{chamado}/atividades/cadastrar
    defaults: { _controller: SuporteTecnicoBundle:Atividade:cadastrar }
    
suporte_atividade_excluir:
    path: /admin/chamado/{chamado}/atividades/{atividade}/excluir
    defaults: { _controller: SuporteTecnicoBundle:Atividade:excluir }
 
# Anotação    
    
suporte_anotacao_cadastrar:
    path: /chamado/{chamado}/anotacoes/cadastrar
    defaults: { _controller: SuporteTecnicoBundle:Anotacao:cadastrar }
    
suporte_anotacao_excluir:
    path: /chamado/{chamado}/anotacoes/{anotacao}/excluir
    defaults: { _controller: SuporteTecnicoBundle:Anotacao:excluir }

# Categoria

suporte_categoria_pesquisar:
    path: /admin/categoria/pesquisar
    defaults: { _controller: SuporteTecnicoBundle:Categoria:pesquisar }
    
suporte_categoria_cadastrar:
    path: /admin/categoria/cadastrar
    defaults: { _controller: SuporteTecnicoBundle:Categoria:cadastrar }
    
suporte_categoria_atualizar:
    path: /admin/categoria/{categoria}/atualizar
    defaults: { _controller: SuporteTecnicoBundle:Categoria:atualizar }

suporte_categoria_editar:
    path: /admin/categoria/{categoria}/editar
    defaults: { _controller: SuporteTecnicoBundle:Categoria:editar }

suporte_categoria_excluir:
    path: /admin/categoria/{categoria}/excluir
    defaults: { _controller: SuporteTecnicoBundle:Categoria:excluir }

suporte_categoria_gerarCombo:
    path: /categoria/combobox
    methods: [POST]
    defaults: { _controller: SuporteTecnicoBundle:Categoria:gerarCombo }

suporte_api_categoria_getSubcategorias:
    path: /admin/categoria/{categoria}/listar-filhas
    defaults: { _controller: SuporteTecnicoBundle:Categoria:getSubcategorias }
 
# Tags

suporte_categoria_tag_listar:
    path: /admin/categoria/{categoria}/tags
    defaults: { _controller: SuporteTecnicoBundle:Tag:listar }
    
suporte_categoria_tag_cadastrar:
    path: /admin/categoria/{categoria}/tags/cadastrar
    defaults: { _controller: SuporteTecnicoBundle:Tag:cadastrar }
    
suporte_categoria_tag_excluir:
    path: /admin/categoria/{categoria}/tags/{tag}/excluir
    defaults: { _controller: SuporteTecnicoBundle:Tag:excluir }
    
# Equipe

suporte_equipe_pesquisar:
    path: /admin/equipe/pesquisar
    defaults: { _controller: SuporteTecnicoBundle:Equipe:pesquisar }
    
suporte_equipe_cadastrar:
    path: /admin/equipe/cadastrar
    defaults: { _controller: SuporteTecnicoBundle:Equipe:cadastrar }
    
suporte_equipe_atualizar:
    path: /admin/equipe/{equipe}/atualizar
    defaults: { _controller: SuporteTecnicoBundle:Equipe:atualizar }

suporte_equipe_atualizarAjax:
    path: /admin/equipe/{equipe}/atualizar/ajax
    defaults: { _controller: SuporteTecnicoBundle:Equipe:atualizarAjax }
    
suporte_equipe_adicionarIntegrante:
    path: /admin/equipe/{equipe}/integrantes/add
    defaults: { _controller: SuporteTecnicoBundle:Equipe:adicionarIntegrante }

suporte_equipe_buscarIntegrante:
    path: /admin/equipe/integrantes/buscar
    defaults: { _controller: SuporteTecnicoBundle:Equipe:buscarPessoa }
    
suporte_equipe_excluirIntegrante:
    path: /admin/equipe/{equipe}/integrantes/{integrante}/remove
    defaults: { _controller: SuporteTecnicoBundle:Equipe:excluirIntegrante }

suporte_equipe_excluir:
    path: /admin/equipe/{equipe}/excluir
    defaults: { _controller: SuporteTecnicoBundle:Equipe:excluir }