parameters:
    intranet_user_provider.class: SME\IntranetBundle\Service\IntranetUserProvider
    intranet_notify: SME\IntranetBundle\Service\NotificationService
    md5_encoder.class: SME\IntranetBundle\Service\MD5Encoder
    intranet_role_hierarchy.class: SME\IntranetBundle\Service\IntranetRoleHierarchy
    intranet_login_moodle.class: SME\IntranetBundle\Listener\LoginListener
    intranet_logout_moodle.class: SME\IntranetBundle\Listener\LogoutListener

services:
    intranet_user_provider:
      class: "%intranet_user_provider.class%"
      arguments: ["@doctrine", "@validator"]
      
    md5_encoder:
      class: "%md5_encoder.class%"
      
    security.role_hierarchy:
      class: "%intranet_role_hierarchy.class%"
      arguments: [%security.role_hierarchy.roles%, "@doctrine"]
      
    security.access.role_voter:
        class:     "Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter"
        arguments: ["@security.role_hierarchy"]
        public:    false
        tags:
            - { name: security.voter }

    security.authentication.success_handler:
      class: "%intranet_login_moodle.class%"
      arguments: ["@router", "@doctrine", "@kernel"]
    
    security.logout.success_handler:
      class: "%intranet_logout_moodle.class%"
      arguments: ["@router", "@doctrine", "@kernel"]
    
    notification:
      class: "%intranet_notify%"
      arguments: ["@doctrine"]