SME\CommonsBundle\Entity\Pessoa:
  properties:
    nome:
      - NotBlank: { message: "O Campo <strong>NOME</strong> é obrigatório." }

SME\CommonsBundle\Entity\Formacao:
  properties:
    nome:
      - NotBlank: { message: "O Campo <strong>NOME DO CURSO</strong> é obrigatório." }
    instituicao:
      - NotBlank: { message: "O Campo <strong>INSTITUIÇÃO</strong> é obrigatório." }
    grauFormacao:
      - NotBlank: { message: "O Campo <strong>GRAU DA FORMAÇÃO</strong> é obrigatório." }