# Ações do servidor

protocolo_servidor_listar:
    path: /meus-protocolos/{categoria}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Servidor:listar }

protocolo_servidor_visualizar:
    path: /consultar/{protocolo}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Servidor:visualizar }

protocolo_servidor_incluirSolicitacao:
    path: /incluir/{solicitacao}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Servidor:incluirSolicitacao }

protocolo_servidor_formSolicitacao:
    path: /incluir
    methods: [GET, POST]
    defaults: { _controller: ProtocoloBundle:Servidor:formSolicitacao }

protocolo_servidor_imprimir:
    path:  /imprimir/{protocolo}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Servidor:imprimir }

# API pública

protocolo_api_getSolicitacoes:
    path: /public/solicitacao
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Public:getRequerimentos }
    
protocolo_api_postProtocolo:
    path: /public/protocolo/{solicitacao}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Public:postProtocolo }
    
protocolo_api_getDocumento:
    path: /public/protocolo/{protocolo}/pdf
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Public:getDocumento }

# Ações de gerenciamento - Protocolo

protocolo_admin_formPesquisa:
    path: /admin/pesquisar/{categoria}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Protocolo:formPesquisa }
    
protocolo_admin_pesquisar:
    path: /admin/pesquisar/{categoria}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Protocolo:pesquisar }

protocolo_admin_consultarRequerente:
    path: /admin/consultar-requerente/{protocolo}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Protocolo:consultarRequerente }

protocolo_admin_visualizar:
    path: /admin/visualizar/{protocolo}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Protocolo:Visualizar }

protocolo_admin_receber:
    path: /admin/receber/{protocolo}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Protocolo:receber }

protocolo_admin_tomarPosse:
    path: /admin/tomar-posse/{protocolo}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Protocolo:tomarPosse }

protocolo_admin_formAtualizacao:
    path: /admin/atualizar/{protocolo}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Protocolo:formAtualizacao }
    
protocolo_admin_atualizar:
    path: /admin/atualizar/{protocolo}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Protocolo:atualizar }

protocolo_admin_formEncaminhamento:
    path: /admin/encaminhar/{protocolo}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Protocolo:formEncaminhamento }
    
protocolo_admin_encaminhar:
    path: /admin/encaminhar/{protocolo}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Protocolo:encaminhar }

protocolo_admin_cancelarEncaminhamento:
    path: /admin/cancelar-encaminhamento/{protocolo}
    methods: [POST]
    defaults: { _controller: ProtocoloBundle:Protocolo:cancelarEncaminhamento }

protocolo_admin_imprimir:
    path: /admin/imprimir/{protocolo}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Protocolo:imprimir }
    
# Ações de gerenciamento - Encaminhamento

protocolo_admin_listarEncaminhamentos:
    path: /admin/encaminhamentos/{categoria}
    methods: [GET]
    defaults: { _controller: ProtocoloBundle:Encaminhamento:listar }
    
protocolo_admin_aceitarEncaminhamento:
    path: /admin/encaminhamentos/aceitar/{encaminhamento}
    methods: [GET, POST]
    defaults: { _controller: ProtocoloBundle:Encaminhamento:aceitar }