VinculoBundle\Entity\Vinculo:
    properties:
        status:
            - Choice: ["ATIVO", "AFASTADO", "DESLIGADO"]
        tipoContrato:
            - Choice: ["EFETIVO", "TEMPORARIO", "COMISSIONADO"]