dgp_servidor_permuta_listarIntencoes:
    path: /servidor/permuta/intencoes
    defaults: { _controller: DGPPermutaBundle:Intencao:listar }
    
dgp_servidor_permuta_cadastrarIntencao:
    path: /servidor/permuta/intencoes/cadastrar
    defaults: { _controller: DGPPermutaBundle:Intencao:cadastrar }
    
dgp_servidor_permuta_excluirIntencao:
    path: /servidor/permuta/intencoes/{intencao}/excluir
    defaults: { _controller: DGPPermutaBundle:Intencao:excluir }
