presenca_index:
    path: /controlepresenca
    defaults: { _controller: PresencaBundle:Presenca:index }

presenca_remover:
    path: /presenca/{id}/remover
    defaults: { _controller: PresencaBundle:Presenca:remover }

presenca_busca:
    path: /buscapresenca
    defaults: { _controller: PresencaBundle:Presenca:busca }

#presenca_buscar:
#    path: /buscarpresencas
#    defaults: { _controller: PresencaBundle:Presenca:buscarPresencas }