parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
       
    ReportBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
    
    twig.report_extension:
        class: ReportBundle\Util\ReportTwigExtension
        tags:
            - { name: twig.extension }
