publicacao_public_getGrupos:
    path: /public/grupos
    defaults: { _controller: PublicacaoBundle:Public:getGrupos }
    
publicacao_public_getCategorias:
    path: /public/grupos/{grupo}/categorias
    defaults: { _controller: PublicacaoBundle:Public:getCategorias }
    
publicacao_public_getDocumento:
    path: /public/documentos/{documento}
    defaults: { _controller: PublicacaoBundle:Public:getDocumento }

# Index

publicacao_index:
    path: /
    defaults: { _controller: PublicacaoBundle:Publicacao:index }

# Grupos

publicacao_grupos:
    path: /grupos
    defaults: { _controller: PublicacaoBundle:Publicacao:listarGrupos }

publicacao_grupos_excluir:
    path: /grupos/{id}/excluir
    defaults: { _controller: PublicacaoBundle:Publicacao:excluirGrupos }
    
publicacao_grupos_editar:
    path: /grupos/{id}/editar
    defaults: { _controller: PublicacaoBundle:Publicacao:editarGrupos }

# Categorias

publicacao_grupos_categorias:
    path: /grupos/categorias
    defaults: { _controller: PublicacaoBundle:Publicacao:listarGruposCategorias }

publicacao_categorias:
    path: /categorias/grupo/{id}
    defaults: { _controller: PublicacaoBundle:Publicacao:listarCategorias }

publicacao_categorias_excluir:
    path: /categoria/{id}/excluir
    defaults: { _controller: PublicacaoBundle:Publicacao:excluirCategorias }
    
publicacao_categorias_editar:
    path: /categoria/{id}/editar
    defaults: { _controller: PublicacaoBundle:Publicacao:editarCategorias }
    
# Sub-Categorias

publicacao_subcategorias:
    path: /subcategorias/{id}
    defaults: { _controller: PublicacaoBundle:Publicacao:listarSubCategorias }

publicacao_subcategorias_excluir:
    path: /subcategoria/{id}/excluir
    defaults: { _controller: PublicacaoBundle:Publicacao:excluirSubCategorias }
    
publicacao_subcategorias_editar:
    path: /subcategoria/{id}/editar
    defaults: { _controller: PublicacaoBundle:Publicacao:editarSubCategorias }

# Publicar

publicacao_raiz:
    path: /raiz
    defaults: { _controller: PublicacaoBundle:Publicacao:publicacaoRaiz }

publicacao_pasta:
    path: /pasta/{id}
    defaults: { _controller: PublicacaoBundle:Publicacao:publicacaoPasta }

publicacao_subpasta:
    path: /subpasta/{id}
    defaults: { _controller: PublicacaoBundle:Publicacao:publicacaoSubPasta }

# Arquivo

publicacao_arquivo_editar:
    path: /arquivo/{id}
    defaults: { _controller: PublicacaoBundle:Publicacao:editarArquivo }

publicacao_arquivo_baixar:
    path: /baixar/{id}
    defaults: { _controller: PublicacaoBundle:Publicacao:baixarArquivo }

publicacao_arquivo_excluir:
    path: /excluir/arquivo/{id}
    defaults: { _controller: PublicacaoBundle:Publicacao:excluirArquivo }