SME\EstagioBundle\Entity\Vaga:
  properties:
    titulo:
      - NotBlank: { message: "O Campo <strong>ETAPA</strong> é obrigatório." }
    disciplina:
      - NotBlank: { message: "O Campo <strong>MODALIDADE</strong> é obrigatório." }
    turno:
      - NotBlank: { message: "O Campo <strong>TURNO</strong> é obrigatório." }
    totalVagas:
      - NotBlank: { message: "O Campo <strong>VAGAS</strong> é obrigatório." }

SME\EstagioBundle\Entity\PedidoUsuario:
  properties:
    nome:
      - NotBlank: { message: "O Campo <strong>NOME</strong> é obrigatório." }
    cpf:
      - NotBlank: { message: "O Campo <strong>CPF</strong> é obrigatório." }
    dataNascimento:
      - NotBlank: { message: "O Campo <strong>DATA DE NASCIMENTO</strong> é obrigatório." }
    email:
      - NotBlank: { message: "O Campo <strong>EMAIL</strong> é obrigatório." }
    instituicao:
      - NotBlank: { message: "O Campo <strong>INSTITUIÇÃO</strong> é obrigatório." }
    curso:
      - NotBlank: { message: "O Campo <strong>CURSO</strong> é obrigatório." }