servicos_publicos:
    path: /servicos-publicos    
    defaults: { _controller: PublicBundle:Public:servicosPublicos }

consulta_fila_unica:
    path: /consulta-fila-unica    
    defaults: { _controller: PublicBundle:Public:consultaFilaUnica }

requerimento_externo:
    path: /requerimento-externo
    defaults: { _controller: PublicBundle:Public:requerimentoExterno }

formacao_externa:
    path: /formacao-externa
    defaults: { _controller: PublicBundle:Public:formacaoExterna }

formacao_externa_matricula:
    path: /formacao-externa/{formacao}/matricula
    defaults: { _controller: PublicBundle:Public:formacaoExternaMatricula }

formacao_externa_consulta:
    path: /formacao-externa/consulta
    defaults: { _controller: PublicBundle:Public:buscaCertificados }

formacao_externa_imprimir_certificado:
    path: /formacao-externa/{matricula}/imprimir-certificado
    defaults: { _controller: PublicBundle:Public:imprimirCertificado }